server:
  port: ${PORT:0}
spring:
  application:
    name: sos-oauth
  output:
    ansi:
      enabled: ALWAYS
eureka:
  client:
    service-url:
      defaultZone: ${URL_SERVICE_DISCOVERY:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}





