server:
  port: ${PORT:0}
spring:
  application:
    name: sos-customer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: ${PROFILE:local}
  output:
    ansi:
      enabled: ALWAYS
  order-service:
    url: http://sos-service-order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
mq:
  queues:
    mq-customer-order-service: mq-customer-order-service

#api:
#  security:
#    token:
#      secret: ${JWT_SECRET:my-secret-key}
# Configuracoes de log

#logging:
#  pattern:
#    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
#  file:
#    name: app.log
#  level:
#    root: warn
#    br:
#      com:
#        bgrbarbosa:
#          catalogo_carros_api: info

# Parametros de configuracoes para rodar em ambiente docker
---
#spring:
#  config:
#    activate:
#      on-profile: docker
#  datasource:
#    url: ${DATASOURCE_URL}
#    username: ${DATASOURCE_USERNAME}
#    password: ${DATASOURCE_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true

# Parametros de configuracoes para rodar em ambiente local
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/sos_customer}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:example}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Parametros de configuracoes para rodar em ambiente de testes
---
#spring:
#  config:
#    activate:
#      on-profile: test
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true




